## Numpy Arrays versus Python Lists
### Yr2 Computing, Andreas Freise
This notebook demonstrates how to use Numpy arrays, in particular as input and output arguments of functions.  

In [1]:
# Relevant imports
import numpy as np
import math 

Numpy arrays and lists are containers that hold a number of other objects in a given order. In the following we discuss lists or Numpy arrays of floating point numbers.

The objects in a Numpy array must all be the same type of data, but the structure is optimised for numerical operations. In particular Numpy arrays allow for faster and easier to code per-element operations, for example:

In [2]:
# creating a Numpy array
x = np.array([3, 6, 9, 12])
# a Numpy array allows easy access to per-element operations such as this:
y = x / 3.0
print(y)

[1. 2. 3. 4.]


If we try the same with a list, we get an error:

In [1]:
# creating a list
x = [3, 6, 9, 12]
y = x / 3.0

TypeError: unsupported operand type(s) for /: 'list' and 'float'

Or worse, sometimes we might not get an error but unexpected results. For example applying multiplication with an integer to a list would produce the following:

In [2]:
# creating a list
x = [3, 6, 9, 12]
y = x * 3
print(y)

[3, 6, 9, 12, 3, 6, 9, 12, 3, 6, 9, 12]


This is clearly not what we intended. Instead, when working with lists, we would have to explictly loop over the list to apply per-element operations, for example like this:

In [5]:
x = [3, 6, 9, 12]
y = []
for e in x:
    y.append (e / 3.0)
print(y)

[1.0, 2.0, 3.0, 4.0]


There are shorter ways of writing similar code, but they are not as clear as using Numpy arrays:

In [6]:
x = [3, 6, 9, 12]
y = [e / 3.0 for e in x]
print(y)

[1.0, 2.0, 3.0, 4.0]


And most importanly this syntax using lists is typically much slower than numpy arrays.

** Defining a Function: Good Example **

When we want to apply a more complex operation to each element of a range of numbers we write a function that use Numpy arrays as input and output argument. For example if we want to apply the operation $$f(x) = 3.0 * \exp(x^2)$$ we can write:

In [7]:
def f(x):
    return 3.0 * np.exp(np.power(x,2))

This function can take a single floating point value as input or a Numpy array, and will return the same data format, for example:

In [8]:
x = [0.3, 0.6, 0.9, 0.12]
y = f(x)
print(y)

[3.28252285 4.29998824 6.74372396 3.04351254]


** Bad Examples **

Below are a few example of how **not** to write a function for Numpy arrays, all taken from previous students' submissions in this course.

In [9]:
y = []
def f_bad1(x):
    for e in x:
        y.append (3.0 * math.exp(e**2))
    return y

x = np.array([0.3, 0.6, 0.9, 0.12])
y = f_bad1(x)
print(y)

[3.2825228511156315, 4.29998824368102, 6.743723960029415, 3.043512538382288]


At first glance this seems to work, but there are several mistakes in this code:
  * The function has a for loop instead of using Numpy-based per-element operations, this will slow down the computation a lot.
  * The function returns a list instead of an array, which here seems to be OK, as we are only printing the result, but if you would try to pass the output data to another function you would get an error
  * The function appends to an array defined outside the function body, so if we were to call this twice we would get a longer array.
  
The two latter problems can be fixed as follows:

In [10]:
def f_bad2(x):
    y = []
    for e in x:
        y.append (3.0 * math.exp(e**2))
    return np.array(y)

x = np.array([0.3, 0.6, 0.9, 0.12])
y = f_bad2(x)
print(y)

[3.28252285 4.29998824 6.74372396 3.04351254]


This technically is a function that accepts and returns a Numpy array and performs the required operation. However, it uses list operations internally and does not correctly implement Numpy per-element operations for arrays. The marking scripts for this course should **not** accept such a function as correct.